spring:
  profiles:
    group:
      maria: "maria,common"

---
spring:
  profiles:
    group:
      mssql: "mssql,common"
---

spring:
  profiles:
    group:
      oracle: "oracle,common"
---
spring:
  profiles:
    group:
      postgre: "postgre,common"
---

spring:
  config:
    activate:
      on-profile: maria
  datasource:
    hikari:
      platform: mariadb
      username: sa
      password: sm1418!1662
      jdbc-url: jdbc:mysql://169.56.72.66:3306/studio?zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.cj.jdbc.Driver
      connectionTimeout : 30000
      auto-commit: false
---
spring:
  config:
    activate:
      on-profile: mssql
  datasource:
    hikari:
      platform: mssql
      username: sa
      password: sm1418!1662
      jdbc-url: jdbc:sqlserver://169.56.72.70:1433;databaseName=sample
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      connectionTimeout : 30000
      auto-commit: false

---

site-url:
  naver : https://www.naver.com
  google : https://google.com
  test : testiiiiiiiiiiiiiiiiiiiiiiiiii
---
jwt:
  encode:
    key: apspeedsmjj1418**00
---
redis:
  host: localhost
  port: 6379


#spring:
#  dbname: maria
#    datasource:
#      hikari:
#        maximum-pool-size : 4
#        url : jdbc:postgresql://169.56.72.66:5438/postgres
#        username : sa
#        password : sm1418!1662